"""news_url to company

Revision ID: 4d1e3f07f6f8
Revises: 6338148aae0c
Create Date: 2023-04-03 13:14:26.983893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1e3f07f6f8'
down_revision = '6338148aae0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('news_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'news_url')
    # ### end Alembic commands ###
